name: Deploy with Helm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: portfolio-app
  EKS_CLUSTER_NAME: portfolio-cluster

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::537124942860:role/github-actions-role
        aws-region: us-west-1
        audience: sts.amazonaws.com
        role-session-name: GitHubActions

    - name: Verify AWS Authentication
      run: |
        echo "Verifying AWS Authentication..."
        aws sts get-caller-identity
        echo "Listing EKS clusters..."
        aws eks list-clusters

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create aws-auth ConfigMap if needed
      run: |
        echo "Checking if github-actions-role is already in the aws-auth ConfigMap..."
        # Create kubeconfig
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        
        # Store current identity info
        ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        ROLE_NAME="github-actions-role"
        ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}"
        
        # Create or update the aws-auth ConfigMap to give the IAM role access to the cluster
        echo "Adding role ${ROLE_ARN} to EKS cluster auth..."
        
        # Download eksctl if it doesn't exist
        if ! command -v eksctl &> /dev/null; then
          echo "Installing eksctl..."
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
        fi
        
        # Add the role to the aws-auth ConfigMap
        eksctl create iamidentitymapping \
          --cluster ${{ env.EKS_CLUSTER_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --arn ${ROLE_ARN} \
          --group system:masters \
          --username github-actions || echo "Role mapping might already exist or failed to create"

    - name: Update kube config 
      run: |
        echo "Updating kubeconfig..."
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        
        echo "Verifying kubeconfig and cluster access..."
        kubectl config get-contexts
        kubectl auth can-i list pods || echo "Can't list pods, insufficient permissions"

    - name: Debug Environment
      run: |
        echo "Using EKS Cluster: ${{ env.EKS_CLUSTER_NAME }}"
        echo "AWS Region: ${{ env.AWS_REGION }}"
        echo "Current directory: $(pwd)"
        ls -la ./kubernetes/helm/app || echo "Helm chart directory not found"
        
    - name: Install/Upgrade Helm Deployment
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Debug information
        echo "Using ECR Registry: $ECR_REGISTRY"
        echo "Using Image Tag: $IMAGE_TAG"
        echo "Using release name: portfolio-app"
        
        # Use Helm to deploy the application
        helm upgrade --install portfolio-app ./kubernetes/helm/app \
          --set image.repository=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }} \
          --set image.tag=$IMAGE_TAG \
          --namespace prod \
          --create-namespace
          
        # Only continue with verification if deployment succeeds
        if [ $? -eq 0 ]; then
          # Wait and verify deployment
          kubectl rollout status deployment/portfolio-app -n prod --timeout=5m
          kubectl get all -n prod
        fi
        
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()