name: Deploy with Helm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: portfolio-app
  EKS_CLUSTER_NAME: portfolio-cluster
  ACCOUNT_ID: "537124942860"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::537124942860:role/github-actions-role
        aws-region: us-west-1
        audience: sts.amazonaws.com
        role-session-name: GitHubActions

    - name: Install AWS CLI
      run: |
        echo "Installing AWS CLI..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Verify AWS Authentication
      run: |
        echo "Verifying AWS Authentication..."
        aws sts get-caller-identity
        echo "Listing EKS clusters..."
        aws eks list-clusters

    - name: Install eksctl and kubectl
      run: |
        # Install kubectl
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
        
        # Install eksctl
        echo "Installing eksctl..."
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version

    - name: Install Helm
      run: |
        echo "Installing Helm..."
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version

    - name: Configure EKS Cluster Access
      run: |
        echo "Configuring EKS Cluster access..."
        
        # Get current credentials
        AWS_CREDS=$(aws sts assume-role --role-arn arn:aws:iam::${ACCOUNT_ID}:role/github-actions-role --role-session-name GithubActionsEKSAccess --output json)
        export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.Credentials.AccessKeyId')
        export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.Credentials.SecretAccessKey')
        export AWS_SESSION_TOKEN=$(echo $AWS_CREDS | jq -r '.Credentials.SessionToken')
        
        # Configure kubectl using eksctl
        eksctl utils write-kubeconfig --cluster=${EKS_CLUSTER_NAME} --region=${AWS_REGION} --set-kubeconfig-context=true
        
        # Verify identity
        echo "Verifying AWS identity..."
        aws sts get-caller-identity
        
        # Test connection
        echo "Testing Kubernetes connection..."
        kubectl cluster-info

    - name: Get ECR Repository URI
      id: ecr-repo
      run: |
        echo "Getting ECR repository URI..."
        ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
        echo "ECR URI: $ECR_URI"
        echo "ecr_uri=$ECR_URI" >> $GITHUB_OUTPUT

    - name: Login to Amazon ECR
      run: |
        echo "Logging in to Amazon ECR..."
        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        echo "ECR login successful"

    - name: Deploy with Helm
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "=========== DEPLOYMENT INFO ==========="
        echo "Image tag: $IMAGE_TAG"
        echo "Using namespace: prod"
        echo "======================================"
        
        # Get ECR Repository URI
        ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
        echo "Full image reference: ${ECR_URI}:${IMAGE_TAG}"
        
        # Check Helm chart directory
        ls -la ./kubernetes/helm/app || echo "Helm chart directory not found"
        
        # Create namespace
        kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
        
        # Verify connection once more
        kubectl cluster-info
        
        # Deploy with Helm 
        helm upgrade --install portfolio-app ./kubernetes/helm/app \
          --set image.repository=${ECR_URI} \
          --set image.tag=${IMAGE_TAG} \
          --namespace prod \
          --create-namespace
        
        # Show results
        kubectl get pods -n prod --ignore-not-found=true
        kubectl get services -n prod --ignore-not-found=true

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()